const KABINA = [
    // RICH SANTEX
    {
        id: 1,
        brand: "RICH SANTEX",
        model: "806 ХВ",
        size: "900x900x215",
        length: 900,
        width: 900,
        height: 2150,
        form: "Полукруг",
        palletType: "Средний",
        glassThickness: 4,
        glassPattern: "Чёрное полоса",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Без наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка"
        ],
        image_1: "/images/kabina/1/1.jpg",
        image_2: "/images/kabina/1/2.jpg"
    },
    {
        id: 2,
        brand: "RICH SANTEX",
        model: "806 ХВ",
        size: "1000x1000x215",
        length: 1000,
        width: 1000,
        height: 2150,
        form: "Полукруг",
        palletType: "Средний",
        glassThickness: 4,
        glassPattern: "Чёрное полоса",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Без наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Нижняя Гусак для умывание"
        ],
        image_1: "/images/kabina/1/1.jpg",
        image_2: "/images/kabina/1/2.jpg"
    },
    {
        id: 3,
        brand: "RICH SANTEX",
        model: "804",
        size: "1000x1000x215",
        length: 1000,
        width: 1000,
        height: 2150,
        form: "Полукруг",
        palletType: "Глубокий",
        glassThickness: 4,
        glassPattern: "Чёрное полоса",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Без наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Нижняя Гусак для умывание"
        ],
        image_1: "/images/kabina/3/1.jpg",
        image_2: "/images/kabina/3/1.jpg"
    },
    {
        id: 4,
        brand: "RICH SANTEX",
        model: "806 SG",
        size: "1000x1000x215",
        length: 1000,
        width: 1000,
        height: 2150,
        form: "Полукруг",
        palletType: "Средний",
        glassThickness: 4,
        glassPattern: "Чёрное полоса",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Светодиодное (LED) освещение верхняя лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Нижняя Гусак для умывание",
            "Светодиодное (LED) освещение отдельно",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Радио",
            "Колонка для душевой кабины",
            "Дозаторы для жидкого мыла",
            "Стул сидение",
            "Массаж для спины",
            "Вентиляция"
        ],
        image_1: "/images/kabina/4/1.jpg",
        image_2: "/images/kabina/4/2.jpg"
    },
    {
        id: 5,
        brand: "RICH SANTEX",
        model: "807 ХВ",
        size: "900x900x215",
        length: 900,
        width: 900,
        height: 2150,
        form: "Полукруг",
        palletType: "Средний",
        glassThickness: 4,
        glassPattern: "Чёрное полоса",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Радио",
            "Колонка для душевой кабины",
            "Дозатор для жидкого мыла",
            "Массаж для спины",
            "Вентиляция"
        ],
        image_1: "/images/kabina/5/1.jpeg",
        image_2: "/images/kabina/5/2.jpeg"
    },
    {
        id: 6,
        brand: "RICH SANTEX",
        model: "807 ХВ",
        size: "1000x1000x215",
        length: 1000,
        width: 1000,
        height: 2150,
        form: "Полукруг",
        palletType: "Средний",
        glassThickness: 4,
        glassPattern: "Чёрное полоса",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Нижняя Гусак для умывание",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Радио",
            "Колонка для душевой кабины",
            "Дозатор для жидкого мыла",
            "Массаж для спины",
            "Вентиляция"
        ],
        image_1: "/images/kabina/5/1.jpeg",
        image_2: "/images/kabina/5/2.jpeg"
    },
    {
        id: 7,
        brand: "RICH SANTEX",
        model: "805",
        size: "900x900x215",
        length: 900,
        width: 900,
        height: 2150,
        form: "Полукруг",
        palletType: "Глубокий",
        glassThickness: 4,
        glassPattern: "Чёрное полоса",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Радио",
            "Колонка для душевой кабины",
            "Дозатор для жидкого мыла",
            "Массаж для спины",
            "Вентиляция"
        ],
        image_1: "/images/kabina/7/1.jpeg",
        image_2: "/images/kabina/7/2.jpeg"
    },
    {
        id: 8,
        brand: "RICH SANTEX",
        model: "805",
        size: "1000x1000x215",
        length: 1000,
        width: 1000,
        height: 2150,
        form: "Полукруг",
        palletType: "Глубокий",
        glassThickness: 4,
        glassPattern: "Чёрное полоса",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Нижняя Гусак для умывание",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Радио",
            "Колонка для душевой кабины",
            "Дозатор для жидкого мыла",
            "Массаж для спины",
            "Вентиляция"
        ],
        image_1: "/images/kabina/7/1.jpeg",
        image_2: "/images/kabina/7/2.jpeg"
    },
    {
        id: 9,
        brand: "RICH SANTEX",
        model: "109",
        size: "1200x850x215",
        length: 1200,
        width: 850,
        height: 2150,
        form: "Квадратная",
        palletType: "Низкий",
        glassThickness: 4,
        glassPattern: "Без рисунка",
        doorsCount: 1,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Полка",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Массаж для спины",
            "Стул сидение",
            "Вентиляция"
        ],
        image_1: "/images/kabina/9/1.jpeg",
        image_2: "/images/kabina/9/2.jpeg"
    },
    {
        id: 10,
        brand: "RICH SANTEX",
        model: "806 H-L",
        size: "1200x1200x215",
        length: 1200,
        width: 1200,
        height: 2150,
        form: "Полукруг",
        palletType: "Низкий",
        glassThickness: 4,
        glassPattern: "Без рисунка",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Светодиодное (LED) освещение верхняя лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Нижняя Гусак для умывание",
            "Светодиодное (LED) освещение отдельно",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Радио",
            "Колонка для душевой кабины",
            "Дозаторы для жидкого мыла",
            "Стул сидение",
            "Массаж для спины",
            "Вентиляция"
        ],
        image_1: "/images/kabina/10/1.jpg",
        image_2: "/images/kabina/10/2.jpg"
    },
    {
        id: 11,
        brand: "RICH SANTEX",
        model: "806 H-H",
        size: "1200x1200x215",
        length: 1200,
        width: 1200,
        height: 2150,
        form: "Полукруг",
        palletType: "Глубокий",
        glassThickness: 4,
        glassPattern: "Без рисунка",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Светодиодное (LED) освещение верхняя лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Нижняя Гусак для умывание",
            "Светодиодное (LED) освещение отдельно",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Радио",
            "Колонка для душевой кабины",
            "Дозаторы для жидкого мыла",
            "Сидение",
            "Массаж для спины",
            "Вентиляция"
        ],
        image_1: "/images/kabina/11/1.jpg",
        image_2: "/images/kabina/11/2.jpg"
    },
    {
        id: 12,
        brand: "RICH SANTEX",
        model: "806 H-H",
        size: "1350x1350x215",
        length: 1350,
        width: 1350,
        height: 2150,
        form: "Полукруг",
        palletType: "Глубокий",
        glassThickness: 4,
        glassPattern: "Без рисунка",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Наворот",
            "Светодиодное (LED) освещение верхняя лейка",
            "Ручная лейка",
            "Зеркала",
            "Полка",
            "Нижняя Гусак для умывание",
            "Светодиодное (LED) освещение отдельно",
            "Светильник душевой кабины, потолочный",
            "Панель управление",
            "Радио",
            "Колонка для душевой кабины",
            "Дозаторы для жидкого мыла",
            "Сидение",
            "Массаж для спины",
            "Вентиляция"
        ],
        image_1: "/images/kabina/11/1.jpg",
        image_2: "/images/kabina/11/2.jpg"
    },

    // UMXIK CABIN
    // Типы поддонов:
    // (13) - Низкий поддон
    // (25) - Средний поддон  
    // (40) - Глубокий поддон

    {
        id: 13,
        brand: "UMXIK CABIN",
        model: "UX-R5090B (13)",
        size: "900x900x215",
        length: 900,
        width: 900,
        height: 2150,
        form: "Полукруг",
        palletType: "Низкий",
        palletHeight: "Низкий (13)", // добавил для ясности
        glassThickness: 4,
        glassPattern: "Без рисунка",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Без наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Полка"
        ],
        image_1: "/images/kabina/13/1.jpg",
        image_2: "/images/kabina/13/2.jpg"
    },
    {
        id: 14,
        brand: "UMXIK CABIN",
        model: "UX-R5090B (25)",
        size: "900x900x215",
        length: 900,
        width: 900,
        height: 2150,
        form: "Полукруг",
        palletType: "Средний",
        palletHeight: "Средний (25)", // добавил для ясности
        glassThickness: 4,
        glassPattern: "Без рисунка",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Без наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Полка"
        ],
        image_1: "/images/kabina/14/1.jpg",
        image_2: "/images/kabina/14/2.jpg"
    },
    {
        id: 15,
        brand: "UMXIK CABIN",
        model: "UX-R5090B (40)",
        size: "900x900x215",
        length: 900,
        width: 900,
        height: 2150,
        form: "Полукруг",
        palletType: "Глубокий",
        palletHeight: "Глубокий (40)", // добавил для ясности
        glassThickness: 4,
        glassPattern: "Без рисунка",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Без наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Полка"
        ],
        image_1: "/images/kabina/15/1.jpg",
        image_2: "/images/kabina/15/2.jpg"
    },
    {
        id: 16,
        brand: "UMXIK CABIN",
        model: "UX-S5090B (13)",
        size: "900x900x215",
        length: 900,
        width: 900,
        height: 2150,
        form: "Квадрат",
        palletType: "Низкий",
        palletHeight: "Низкий (13)", // добавил для ясности
        glassThickness: 4,
        glassPattern: "Без рисунка",
        doorsCount: 2,
        profileColor: "Чёрный",
        profileMaterial: "Алюминий",
        doorDesign: "Раздвижная",
        openingMechanism: "Ролики скольжения",
        equipment: [
            "Без наворот",
            "Верхняя Лейка",
            "Ручная лейка",
            "Полка"
        ],
        image_1: "/images/kabina/16/1.jpg",
        image_2: "/images/kabina/16/2.jpg"
    }
];

export default KABINA;