const TOILETS = [
    {
        id: 1,
        model: '0401/CLASSICO',
        type: 'Унитаз',
        height: 400,
        length: 620,
        width: 370,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка с микролифтом Китай',
        fittings: 'Арматура Китай',
        price: 41,
        image: '/images/toilets/toilet-1.jpg'
    },
    {
        id: 2,
        model: '0402/GRAZIA',
        type: 'Унитаз',
        height: 400,
        length: 570,
        width: 345,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка (PP) АО «Уклад» Россия',
        fittings: 'Арматура «ИнкоЭр» Россия',
        price: 74,
        image: '/images/toilets/toilet-2.jpg'
    },
    {
        id: 3,
        model: '0405',
        type: 'Унитаз',
        height: 400,
        length: 660,
        width: 370,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка (PP) АО «Уклад» Россия',
        fittings: 'Арматура «ИнкоЭр» Россия',
        price: 36,
        image: '/images/toilets/toilet-3.jpg'
    },
    {
        id: 4,
        model: '0421/ETUDE',
        type: 'Унитаз',
        height: 410,
        length: 640,
        width: 350,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка R&T (PP) Китай',
        fittings: 'Арматура «ИнкоЭр» Россия',
        price: 70,
        image: '/images/toilets/toilet-4.jpg'
    },
    {
        id: 5,
        model: '0422/ELEGANTE',
        type: 'Унитаз',
        height: 400,
        length: 690,
        width: 370,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка R&T (PP) Китай',
        fittings: 'Арматура «ИнкоЭр» Россия',
        price: 70,
        image: '/images/toilets/toilet-5.jpg'
    },
    {
        id: 6,
        model: '0423/Tenerezza',
        type: 'Унитаз',
        height: 407,
        length: 635,
        width: 360,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка R&T (PP) Китай',
        fittings: 'Арматура «ИнкоЭр» Россия',
        price: 70,
        image: '/images/toilets/toilet-6.jpg'
    },
    {
        id: 7,
        model: '0700/Serenata',
        type: 'Унитаз',
        height: 375,
        length: 518,
        width: 365,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка R&T (PP) Китай',
        fittings: 'Крепления Турция',
        price: 45,
        image: '/images/toilets/toilet-7.jpg'
    },
    {
        id: 8,
        model: '0710/Charm',
        type: 'Унитаз',
        height: 360,
        length: 530,
        width: 360,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка R&T (PP) Китай',
        fittings: 'Крепления Турция',
        price: 50,
        image: '/images/toilets/toilet-8.jpg'
    },
    {
        id: 9,
        model: '0800/PRIMO',
        type: 'Унитаз',
        height: 340,
        length: 525,
        width: 360,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Крышка R&T (UF) Китай',
        fittings: 'Крепления Турция',
        price: 51,
        image: '/images/toilets/toilet-9.jpg'
    },
    {
        id: 10,
        model: '0601',
        type: 'Биде',
        height: 390,
        length: 545,
        width: 305,
        glaze: 'Испания',
        color: 'Белый (касабланка)',
        lid: 'Без крышки',
        fittings: 'Стандарт',
        price: 45,
        image: '/images/toilets/bidet-1.jpg'
    }
];

export default TOILETS;